export const SAVE_NAVLIST = 'save_navlist'
export const SAVE_INDEXLIST = 'save_indexlist'
export const SAVE_CATELISTS = 'save_catelists'
export const SAVE_SEARCHLIST = 'save_searchlist'
export const SAVE_BUYLIST = 'save_buylist'
export const SAVE_PUBULIST = 'save_pubulist'
